In [3]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\91942\Downloads\datasets1\datasets1\nba.csv')
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,06-Feb,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,06-Jun,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,06-May,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,06-May,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,06-Oct,231,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41,PF,20,06-Oct,234,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8,PG,26,06-Mar,203,Butler,2433333.0
454,Raul Neto,Utah Jazz,25,PG,24,06-Jan,179,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21,C,26,07-Mar,256,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24,C,26,7-0,231,Kansas,947276.0

In [4]:
s2 = pd.Series(['df.age', 'df.salary'])
s2

0       df.age
1    df.salary
dtype: object

In [5]:
s1 = pd.Series(['john', 'mac'])
s2 = pd.Series([25, 30])
df = pd.concat([s1, s2], axis = 1)
df

      0   1
0  john  25
1   mac  30

In [6]:
import numpy as np
arr = np.array([1,2,3,-5,10])
arr

array([ 1,  2,  3, -5, 10])

In [8]:
ser = pd.Series(arr)
ser

0     1
1     2
2     3
3    -5
4    10
dtype: int64

In [9]:
# convert series into arr
arr1 = ser.values
arr1

array([ 1,  2,  3, -5, 10])

In [10]:
mydict = {'name':['john', 'michel', 'anil','ajay'],
          'dept': ['cse','civil','mechanical','entc'],
          'age': [20,30,40]}
mydict

{'name': ['john', 'michel', 'anil', 'ajay'],
 'dept': ['cse', 'civil', 'mechanical', 'entc'],
 'age': [20, 30, 40]}

In [12]:
arr2 = pd.Series(mydict)
arr2

name        [john, michel, anil, ajay]
dept    [cse, civil, mechanical, entc]
age                       [20, 30, 40]
dtype: object

In [14]:
arr2['name'][0]

'john'